name: Load Data - Create Tags

on:
  workflow_dispatch: # Trigger manually

jobs:
  create-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create 100 tags
        run: |
          for i in $(seq 0 500); do
            tag="6.0.$i"
            git tag $tag
            echo "Created tag: $tag"
          done
          git push --tags
          
      - name: Create year-based tags
        run: |
          for i in $(seq 0 1000); do
            git tag 2024.09.$i
            git tag 2025.09.$i
          done

      - name: Create development tags
        run: |
          for i in $(seq 1 500); do
            git tag develop.$i
          done          
