name: Load Data - Create Tags

on:
  workflow_dispatch: # Trigger manually

jobs:
  create-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create 100 tags
        run: |
          for i in $(seq 0 99); do
            tag="3.0.$i"
            git tag $tag
            echo "Created tag: $tag"
          done
          git push --tags
