# This is a basic workflow to help you get started with Actions

name: CI
run-name: CI
#
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Step 2: Run the semantic versioning action
      - name: Generate Semantic Version
        uses: impks27/demo-semantic-version@main # Replace with your action's repo and version
        id: semantic-version
        with:
          branch: ${{ github.ref_name }}

      # Step 3: Use the generated version in the application
      - name: Print Generated Version
        run: |
           echo "Generated Version: ${{ steps.semantic-version.outputs.version }}"  

      - uses: P4dr4/create-git-tag-action@v1.0.0
        with:
          tag: ${{ steps.semantic-version.outputs.version }}
          message: "Release ${{ steps.semantic-version.outputs.version }}"
